### ISSUE TITLE
Consider pinning the SDK version

### ISSUE THREAD

**Issue by edgarrmondragon** [z3z1ma/target-bigquery#21]
Singer taps and targets are end-user tools rather than libraries, so it makes sense to ship them with pinned versions, or at least only allow patch updates.

**Comment by z3z1ma** [comment]
So I'll pin the version. The reasoning behind not pinning to an exact version is because the release cadence is quite often so I didn't want users to not be able to experience those benefits and bug fixes if I were delayed on updating the target pins. That in combination with the fact users can specify an SDK pin themselves in the pip_url gives them flexibility in the event the target is not updated. In hindsight though, it's also obviously a recipe for non obvious breakage. And with an increasing user base we need an exact pin there.
